package lanat.parsing.errors;

import lanat.utils.ErrorsContainer;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.List;

/**
 * Handles all errors generated by the parser and tokenizer.
 */
public class ErrorsCollector {
	private final List<ErrorHandler<?>> errors = new ArrayList<>();

	public void collectErrors(@NotNull ErrorsContainer<ErrorHandler<?>> errorsContainer) {
		this.errors.addAll(errorsContainer.getErrorsUnderDisplayLevel());
	}

	public List<String> handleErrors() {
		for (var error : this.errors) {
			if (error instanceof ErrorHandler.TokenizeErrorHandler tokenizeError) {
				tokenizeError.handle();
			} else if (error instanceof ErrorHandler.ParseErrorHandler parseError) {
				parseError.handle();
			}
		}
	}
}